//Autor: Manuel Schmocker
//Datum: 17.12.2023
package ch.manuel.structurecalc2d;

//Klasse zum Generieren einer Struktur
import java.awt.Image;
import java.awt.Toolkit;

//Eingabefenser erstellen neuen Stab "Structure Generator"
public class NewJDialog5 extends javax.swing.JDialog {

  private double eModul;          //E-Modul
  private double surface;         //Fläche Stabquerschnitt
  private double x0;              //x-Position 
  private double y0;              //y-Position 
  private int nbElements;         //Anzahl Elemente
  private int nbElements0;        //Anzahl Elemente vertikal
  private double b;               //Breite b eines Elements
  private double h;               //Höhe h eines Elements
  private double h1;              //Höhe h1 eines Elements
  private double h2;              //Höhe h2 eines Elements
  private double f;               //Kraft f
  private double f0;              //Einzellast f0
  // icon in resources
  private static final String ICON = "/icon/icon.png";

  //Konstruktor
  public NewJDialog5(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setIcon();
  }

  // PRIVATE FUNCTIONS
  // set icon
  private void setIcon() {
    Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource(ICON));
    this.setIconImage(image);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    buttonGroup2 = new javax.swing.ButtonGroup();
    buttonGroup3 = new javax.swing.ButtonGroup();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jPanel5 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jRadioButton_Str1 = new javax.swing.JRadioButton();
    jLabel22 = new javax.swing.JLabel();
    jRadioButton_Str2A = new javax.swing.JRadioButton();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jRadioButton_Str2B = new javax.swing.JRadioButton();
    jLabel13 = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    jRadioButton_Str2C = new javax.swing.JRadioButton();
    jLabel37 = new javax.swing.JLabel();
    jRadioButton_Str3A = new javax.swing.JRadioButton();
    jLabel38 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jTextField8 = new javax.swing.JTextField();
    jTextField9 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel39 = new javax.swing.JLabel();
    jTextField12 = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel18 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jRadioButton_Sys1 = new javax.swing.JRadioButton();
    jRadioButton_Sys3 = new javax.swing.JRadioButton();
    jLabel25 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    jLabel27 = new javax.swing.JLabel();
    jRadioButton_Sys2 = new javax.swing.JRadioButton();
    jRadioButton_Sys4 = new javax.swing.JRadioButton();
    jRadioButton_Sys5 = new javax.swing.JRadioButton();
    jLabel40 = new javax.swing.JLabel();
    jRadioButton_Sys6 = new javax.swing.JRadioButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel28 = new javax.swing.JLabel();
    jLabel29 = new javax.swing.JLabel();
    jLabel30 = new javax.swing.JLabel();
    jLabel31 = new javax.swing.JLabel();
    jRadioButton_f1 = new javax.swing.JRadioButton();
    jRadioButton_f2 = new javax.swing.JRadioButton();
    jRadioButton_f3 = new javax.swing.JRadioButton();
    jLabel32 = new javax.swing.JLabel();
    jLabel33 = new javax.swing.JLabel();
    jTextField10 = new javax.swing.JTextField();
    jLabel34 = new javax.swing.JLabel();
    jLabel35 = new javax.swing.JLabel();
    jTextField11 = new javax.swing.JTextField();
    jLabel36 = new javax.swing.JLabel();
    jLabel41 = new javax.swing.JLabel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jLabel19 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jTextField6 = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jTextField7 = new javax.swing.JTextField();

    setResizable(false);

    jButton1.setText("OK");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Abbrechen");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Str1.png"))); // NOI18N

    jLabel21.setText("Einfache Struktur");

    buttonGroup1.add(jRadioButton_Str1);
    jRadioButton_Str1.setSelected(true);
    jRadioButton_Str1.setText("Typ 1A");
    jRadioButton_Str1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton_Str1ActionPerformed(evt);
      }
    });

    jLabel22.setText("Doppelte Struktur");

    buttonGroup1.add(jRadioButton_Str2A);
    jRadioButton_Str2A.setText("Typ 2A");
    jRadioButton_Str2A.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton_Str2AActionPerformed(evt);
      }
    });

    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Str2.png"))); // NOI18N

    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Str3.png"))); // NOI18N

    jLabel23.setText("Doppelte Struktur");

    buttonGroup1.add(jRadioButton_Str2B);
    jRadioButton_Str2B.setText("Typ 2B");
    jRadioButton_Str2B.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton_Str2BActionPerformed(evt);
      }
    });

    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Str4.png"))); // NOI18N

    jLabel24.setText("Doppelte Struktur");

    buttonGroup1.add(jRadioButton_Str2C);
    jRadioButton_Str2C.setText("Typ 2C");
    jRadioButton_Str2C.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton_Str2CActionPerformed(evt);
      }
    });

    jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Str5.png"))); // NOI18N

    buttonGroup1.add(jRadioButton_Str3A);
    jRadioButton_Str3A.setText("Typ 3A");
    jRadioButton_Str3A.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButton_Str3AActionPerformed(evt);
      }
    });

    jLabel38.setText("Mehrfache Struktur");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel10)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel37)
              .addComponent(jLabel11)
              .addComponent(jLabel12)
              .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel21)
          .addComponent(jRadioButton_Str1)
          .addComponent(jLabel22)
          .addComponent(jRadioButton_Str2A)
          .addComponent(jLabel23)
          .addComponent(jRadioButton_Str2B)
          .addComponent(jLabel24)
          .addComponent(jRadioButton_Str2C)
          .addComponent(jRadioButton_Str3A)
          .addComponent(jLabel38))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel5Layout.createSequentialGroup()
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel10)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel21)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton_Str1)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel11)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel22)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton_Str2A)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel12)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel23)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton_Str2B)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel13)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel24)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton_Str2C)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel37)
          .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(jLabel38)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton_Str3A)))
        .addGap(0, 0, Short.MAX_VALUE))
    );

    jScrollPane1.setViewportView(jPanel5);

    jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel20.setText("Paramter für Struktur:");

    jLabel14.setText("Höhe h1");

    jLabel15.setText("Höhe h2");

    jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField8.setText("1.2");
    jTextField8.setEnabled(false);

    jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField9.setText("1.8");
    jTextField9.setEnabled(false);

    jLabel4.setText("x0");

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("y0");

    jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField1.setText("5");
    jTextField1.setPreferredSize(new java.awt.Dimension(80, 20));

    jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField5.setText("0.0");

    jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField3.setText("1.5");

    jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField2.setText("1.0");

    jLabel2.setText("Höhe h");

    jLabel1.setText("Anzahl");

    jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField4.setText("0.0");

    jLabel3.setText("Breite b");

    jLabel39.setText("Anzahl N0");

    jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField12.setText("5");
    jTextField12.setEnabled(false);
    jTextField12.setPreferredSize(new java.awt.Dimension(80, 20));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel20)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel15)
              .addComponent(jLabel14)
              .addComponent(jLabel3)
              .addComponent(jLabel2)
              .addComponent(jLabel4)
              .addComponent(jLabel1)
              .addComponent(jLabel5)
              .addComponent(jLabel39))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel20)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel39))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4)
              .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3)
              .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2)
              .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel14)
              .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel15)
              .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Struktur", jPanel1);

    jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel18.setText("Statisches System:");

    jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lager1.png"))); // NOI18N

    jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lager2.png"))); // NOI18N

    buttonGroup2.add(jRadioButton_Sys1);
    jRadioButton_Sys1.setSelected(true);
    jRadioButton_Sys1.setText("1) Einfacher Balken");

    buttonGroup2.add(jRadioButton_Sys3);
    jRadioButton_Sys3.setText("3) Beidseitig eingespannt");

    jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lager3.png"))); // NOI18N

    jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lager4.png"))); // NOI18N

    jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lager5.png"))); // NOI18N

    buttonGroup2.add(jRadioButton_Sys2);
    jRadioButton_Sys2.setText("2) Einfacher Balken + Auskragung");

    buttonGroup2.add(jRadioButton_Sys4);
    jRadioButton_Sys4.setText("4) Eingespannt + Auskragung");

    buttonGroup2.add(jRadioButton_Sys5);
    jRadioButton_Sys5.setText("5) Einseitig eingespannt");

    jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lager6.png"))); // NOI18N

    buttonGroup2.add(jRadioButton_Sys6);
    jRadioButton_Sys6.setText("6) Alle Punkte fixiert (unten)");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel17)
              .addComponent(jLabel25)
              .addComponent(jLabel26)
              .addComponent(jLabel27)
              .addComponent(jLabel16)
              .addComponent(jLabel40))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jRadioButton_Sys1)
              .addComponent(jRadioButton_Sys2)
              .addComponent(jRadioButton_Sys3)
              .addComponent(jRadioButton_Sys4)
              .addComponent(jRadioButton_Sys5)
              .addComponent(jRadioButton_Sys6)))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel18)))
        .addContainerGap(212, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jRadioButton_Sys1)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel18)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25))
              .addComponent(jRadioButton_Sys2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jRadioButton_Sys3, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel26))
          .addComponent(jRadioButton_Sys4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel16)
          .addComponent(jRadioButton_Sys5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel40)
          .addComponent(jRadioButton_Sys6))
        .addContainerGap(89, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Lager", jPanel2);

    jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel28.setText("Kräfte");

    jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Force1.png"))); // NOI18N

    jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Force2.png"))); // NOI18N

    jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Force3.png"))); // NOI18N

    buttonGroup3.add(jRadioButton_f1);
    jRadioButton_f1.setSelected(true);
    jRadioButton_f1.setText("Verteilte Last");

    buttonGroup3.add(jRadioButton_f2);
    jRadioButton_f2.setText("Einzellast");

    buttonGroup3.add(jRadioButton_f3);
    jRadioButton_f3.setText("Verteilte Last + Einzellast");

    jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel32.setText("Lasten:");

    jLabel33.setText("Kraft F");

    jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField10.setText("-100.0");

    jLabel34.setText("kN");

    jLabel35.setText("kN");

    jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField11.setText("-250.0");

    jLabel36.setText("Kraft F0");

    jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Force4.png"))); // NOI18N

    buttonGroup3.add(jRadioButton1);
    jRadioButton1.setText("Verteilte horiz. + vert. Last");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel30)
              .addComponent(jLabel31)
              .addComponent(jLabel41))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jRadioButton_f1)
              .addComponent(jRadioButton_f2)
              .addComponent(jRadioButton_f3)
              .addComponent(jRadioButton1)))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel28))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel33)
                .addGap(33, 33, 33)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel34)
              .addComponent(jLabel35)))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel32))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel29)))
        .addContainerGap(219, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel28)
        .addGap(11, 11, 11)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jRadioButton_f3)
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabel29)
                      .addComponent(jRadioButton_f1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel30))
                  .addComponent(jRadioButton_f2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel41))
          .addComponent(jRadioButton1))
        .addGap(18, 18, 18)
        .addComponent(jLabel32)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel33)
          .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel34))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel35)
          .addComponent(jLabel36))
        .addContainerGap(46, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Kräfte", jPanel3);

    jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel19.setText("Eigenschaften Querschnitt:");

    jLabel7.setText("Fläche");

    jLabel6.setText("E-Modul");

    jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField6.setText("2000.0");

    jLabel8.setText("mm2");

    jLabel9.setText("GPa");

    jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    jTextField7.setText("210000.0");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel19)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel9))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel8)))))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel19)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jLabel9)
          .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  //OK gedrückt
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      checkInput();
      this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

  //jRadioButton_Str2A gedrück: h1 und h2 deaktivieren
  //Doppelte Struktur: Typ 2A
    private void jRadioButton_Str2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Str2AActionPerformed
      if (jRadioButton_Str2A.isSelected()) {
        jTextField3.setEnabled(false);
        jTextField8.setEnabled(true);
        jTextField9.setEnabled(true);
        jTextField12.setEnabled(false);
      }
    }//GEN-LAST:event_jRadioButton_Str2AActionPerformed

  //jRadioButton_Str1 gedrückt: h1 und h2 deaktivieren
  //Einfache Struktur: Typ 1A
    private void jRadioButton_Str1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Str1ActionPerformed
      if (jRadioButton_Str1.isSelected()) {
        jTextField3.setEnabled(true);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField12.setEnabled(false);
      }
    }//GEN-LAST:event_jRadioButton_Str1ActionPerformed

  //jRadioButton_Str2B gedrück: h1 und h2 deaktivieren
  //Doppelte Struktur: Typ 2B
    private void jRadioButton_Str2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Str2BActionPerformed
      if (jRadioButton_Str2B.isSelected()) {
        jTextField3.setEnabled(false);
        jTextField8.setEnabled(true);
        jTextField9.setEnabled(true);
        jTextField12.setEnabled(false);
      }
    }//GEN-LAST:event_jRadioButton_Str2BActionPerformed

  //jRadioButton_Str2C gedrück: h1 und h2 deaktivieren
  //Doppelte Struktur: Typ 2C
    private void jRadioButton_Str2CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Str2CActionPerformed
      if (jRadioButton_Str2C.isSelected()) {
        jTextField3.setEnabled(false);
        jTextField8.setEnabled(true);
        jTextField9.setEnabled(true);
        jTextField12.setEnabled(false);
      }
    }//GEN-LAST:event_jRadioButton_Str2CActionPerformed

    private void jRadioButton_Str3AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_Str3AActionPerformed
      if (jRadioButton_Str3A.isSelected()) {
        jTextField3.setEnabled(true);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField12.setEnabled(true);
      }
    }//GEN-LAST:event_jRadioButton_Str3AActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.ButtonGroup buttonGroup2;
  private javax.swing.ButtonGroup buttonGroup3;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel27;
  private javax.swing.JLabel jLabel28;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel32;
  private javax.swing.JLabel jLabel33;
  private javax.swing.JLabel jLabel34;
  private javax.swing.JLabel jLabel35;
  private javax.swing.JLabel jLabel36;
  private javax.swing.JLabel jLabel37;
  private javax.swing.JLabel jLabel38;
  private javax.swing.JLabel jLabel39;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel40;
  private javax.swing.JLabel jLabel41;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton_Str1;
  private javax.swing.JRadioButton jRadioButton_Str2A;
  private javax.swing.JRadioButton jRadioButton_Str2B;
  private javax.swing.JRadioButton jRadioButton_Str2C;
  private javax.swing.JRadioButton jRadioButton_Str3A;
  private javax.swing.JRadioButton jRadioButton_Sys1;
  private javax.swing.JRadioButton jRadioButton_Sys2;
  private javax.swing.JRadioButton jRadioButton_Sys3;
  private javax.swing.JRadioButton jRadioButton_Sys4;
  private javax.swing.JRadioButton jRadioButton_Sys5;
  private javax.swing.JRadioButton jRadioButton_Sys6;
  private javax.swing.JRadioButton jRadioButton_f1;
  private javax.swing.JRadioButton jRadioButton_f2;
  private javax.swing.JRadioButton jRadioButton_f3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField10;
  private javax.swing.JTextField jTextField11;
  private javax.swing.JTextField jTextField12;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private javax.swing.JTextField jTextField8;
  private javax.swing.JTextField jTextField9;
  // End of variables declaration//GEN-END:variables

  //Eingabe prüfen und Berechnung starten
  private void checkInput() {
    String str;                 //Inhalt Text-Feld
    boolean inputOK = true;     //Fehler beim Auslesen

    //E-Modul auslesen
    str = jTextField7.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      eModul = Double.parseDouble(str);   //Keine negativen Werte
      if (eModul <= 0) {
        eModul = 210000;
        jTextField7.setText(Double.toString(eModul));
      }
    } else {
      inputOK = false;
    }

    //Fläche auslesen
    str = jTextField6.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      surface = Double.parseDouble(str);  //Keine negativen Werte
      if (surface <= 0) {
        surface = 1000;
        jTextField6.setText(Double.toString(surface));
      }
    } else {
      inputOK = false;
    }

    //x0 auslesen
    str = jTextField4.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      x0 = Double.parseDouble(str);
    } else {
      inputOK = false;
    }

    //y0 auslesen
    str = jTextField5.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      y0 = Double.parseDouble(str);
    } else {
      inputOK = false;
    }

    //N (Anzahl) auslesen
    str = jTextField1.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isInteger(str)) {
      nbElements = Integer.parseInt(str); //Keine negativen Werte
      if (nbElements <= 0) {
        nbElements = 1;
        jTextField1.setText(Integer.toString(nbElements));
      }
    } else {
      inputOK = false;
    }

    //N0 (Anzahl) auslesen
    str = jTextField12.getText();       //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isInteger(str)) {
      nbElements0 = Integer.parseInt(str); //Keine negativen Werte
      if (nbElements0 <= 0) {
        nbElements0 = 1;
        jTextField12.setText(Integer.toString(nbElements0));
      }
    } else {
      inputOK = false;
    }

    //h (Höhe) auslesen
    str = jTextField3.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      h = Double.parseDouble(str);    //Keine negativen Werte
      if (h <= 0) {
        h = 1.0;
        jTextField3.setText(Double.toString(h));
      }
    } else {
      inputOK = false;
    }

    //h1 (Höhe) auslesen
    str = jTextField8.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      h1 = Double.parseDouble(str);   //Keine negativen Werte
      if (h1 <= 0) {
        h1 = 1.0;
        jTextField8.setText(Double.toString(h1));
      }
    } else {
      inputOK = false;
    }

    //h2 (Höhe) auslesen
    str = jTextField9.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      h2 = Double.parseDouble(str);   //Keine negativen Werte
      if (h2 <= 0) {
        h2 = 1.0;
        jTextField9.setText(Double.toString(h2));
      }
    } else {
      inputOK = false;
    }

    //b (Breite) auslesen
    str = jTextField2.getText();        //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      b = Double.parseDouble(str);    //Keine negativen Werte
      if (b <= 0) {
        b = 1.0;
        jTextField2.setText(Double.toString(b));
      }
    } else {
      inputOK = false;
    }

    //f (Kraft) auslesen
    str = jTextField10.getText();           //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      f = Double.parseDouble(str);
    }

    //f0 (Kraft) auslesen
    str = jTextField11.getText();           //Kann die Eingabe numerisch interpretiert werden?
    if (MyUtilities.isNumeric(str)) {
      f0 = Double.parseDouble(str);
    } else {
      inputOK = false;
    }
    //Surf. und Mod. in Section eintragen
    NewJDialog2.addValue(surface, eModul);

    //Struktur erzeugen
    if (inputOK) {
      Structure.clearStruct();        //Struktur zurücksetzten

      if (jRadioButton_Str1.isSelected()) {
        //Struktur1 generieren
        generateStructure1();
      } else if (jRadioButton_Str2A.isSelected()) {
        //Struktur2A generieren
        generateStructure2();
      } else if (jRadioButton_Str2B.isSelected()) {
        //Struktur2B generieren
        generateStructure3();
      } else if (jRadioButton_Str2C.isSelected()) {
        //Struktur2C generieren
        generateStructure4();
      } else {
        //Struktur3A generieren
        generateStructure5();
      }

      Main.myFrame.updateMyPlot();
    }
  }

  //Struktur 1 generieren
  private void generateStructure1() {
    Structure.addPoint(x0, y0);     //Punkt 0
    Structure.addPoint(x0, y0 + h); //Punkt 1
    //Verbinden
    Structure.addBeam(Structure.getPt(0), Structure.getPt(1), eModul, surface);

    double dx;
    for (int i = 0; i < nbElements; i++) {
      dx = x0 + (i + 1) * b;

      Structure.addPoint(dx, y0);         //Punkt 2*i+2, unten
      Structure.addPoint(dx, y0 + h);     //Punkt 2*i+3, oben
      //Verbinden
      Structure.addBeam(Structure.getPt(2 * i + 2), Structure.getPt(2 * i + 1), eModul, surface);     //Diagonal
      Structure.addBeam(Structure.getPt(2 * i + 3), Structure.getPt(2 * i), eModul, surface);       //Diagonal
      Structure.addBeam(Structure.getPt(2 * i + 3), Structure.getPt(2 * i + 2), eModul, surface);     //vertikal
      Structure.addBeam(Structure.getPt(2 * i + 3), Structure.getPt(2 * i + 1), eModul, surface);     //horizontal oben
      Structure.addBeam(Structure.getPt(2 * i + 2), Structure.getPt(2 * i), eModul, surface);       //horizontal unten
    }

    //Lagerung festlegen: Anz. horiz. Balken: 2
    setFix(2);
    setForce(2);
  }

  //Struktur 2 generieren
  private void generateStructure2() {
    Structure.addPoint(x0, y0);             //Punkt 0
    Structure.addPoint(x0, y0 + h2);        //Punkt 1
    Structure.addPoint(x0, y0 + h2 + h1);   //Punkt 2
    //Verbinden
    Structure.addBeam(Structure.getPt(0), Structure.getPt(1), eModul, surface);
    Structure.addBeam(Structure.getPt(1), Structure.getPt(2), eModul, surface);

    double dx;
    for (int i = 0; i < nbElements; i++) {
      dx = x0 + (i + 1) * b;

      Structure.addPoint(dx, y0);                 //Punkt 3*i+3 (unten)
      Structure.addPoint(dx, y0 + h2);            //Punkt 3*i+4 (mitte)
      Structure.addPoint(dx, y0 + h2 + h1);       //Punkt 3*i+5 (oben)
      //Verbinden
      Structure.addBeam(Structure.getPt(3 * i + 2), Structure.getPt(3 * i + 4), eModul, surface);     //Diagonal
      Structure.addBeam(Structure.getPt(3 * i + 1), Structure.getPt(3 * i + 5), eModul, surface);     //Diagonal
      Structure.addBeam(Structure.getPt(3 * i), Structure.getPt(3 * i + 4), eModul, surface);       //Diagonal
      Structure.addBeam(Structure.getPt(3 * i + 1), Structure.getPt(3 * i + 3), eModul, surface);     //Diagonal
      Structure.addBeam(Structure.getPt(3 * i + 5), Structure.getPt(3 * i + 4), eModul, surface);     //vertikal oben
      Structure.addBeam(Structure.getPt(3 * i + 4), Structure.getPt(3 * i + 3), eModul, surface);     //vertikal unten
      Structure.addBeam(Structure.getPt(3 * i + 5), Structure.getPt(3 * i + 2), eModul, surface);     //horizontal oben
      Structure.addBeam(Structure.getPt(3 * i + 4), Structure.getPt(3 * i + 1), eModul, surface);     //horizontal mitte
      Structure.addBeam(Structure.getPt(3 * i + 3), Structure.getPt(3 * i), eModul, surface);       //horizontal unten
    }

    //Lagerung festlegen
    //Anz. horiz. Balken: 3
    setFix(3);
    setForce(3);
  }

  //Struktur 3 generieren
  private void generateStructure3() {
    Structure.addPoint(x0, y0);             //Punkt 0
    Structure.addPoint(x0, y0 + h2);        //Punkt 1
    Structure.addPoint(x0, y0 + h2 + h1);   //Punkt 2
    //Verbinden
    Structure.addBeam(Structure.getPt(0), Structure.getPt(1), eModul, surface);
    Structure.addBeam(Structure.getPt(1), Structure.getPt(2), eModul, surface);

    double dx;
    for (int i = 0; i < nbElements; i++) {
      dx = x0 + (i + 1) * b;

      Structure.addPoint(dx, y0);                 //Punkt 3*i+3 (unten)
      Structure.addPoint(dx, y0 + h2);            //Punkt 3*i+4 (mitte)
      Structure.addPoint(dx, y0 + h2 + h1);       //Punkt 3*i+5 (oben)
      //Verbinden
      Structure.addBeam(Structure.getPt(3 * i + 5), Structure.getPt(3 * i + 4), eModul, surface);     //vertikal oben
      Structure.addBeam(Structure.getPt(3 * i + 4), Structure.getPt(3 * i + 3), eModul, surface);     //vertikal unten
      Structure.addBeam(Structure.getPt(3 * i + 5), Structure.getPt(3 * i + 2), eModul, surface);     //horizontal oben
      Structure.addBeam(Structure.getPt(3 * i + 4), Structure.getPt(3 * i + 1), eModul, surface);     //horizontal mitte
      Structure.addBeam(Structure.getPt(3 * i + 3), Structure.getPt(3 * i), eModul, surface);       //horizontal unten
      if ((i % 2) == 0) {
        Structure.addBeam(Structure.getPt(3 * i + 2), Structure.getPt(3 * i + 4), eModul, surface);     //Diagonal
        Structure.addBeam(Structure.getPt(3 * i), Structure.getPt(3 * i + 4), eModul, surface);       //Diagonal
      } else {
        Structure.addBeam(Structure.getPt(3 * i + 1), Structure.getPt(3 * i + 5), eModul, surface);     //Diagonal
        Structure.addBeam(Structure.getPt(3 * i + 1), Structure.getPt(3 * i + 3), eModul, surface);     //Diagonal
      }
    }

    //Lagerung festlegen
    //Anz. horiz. Balken: 3
    setFix(3);
    setForce(3);
  }

  //Struktur 4 generieren
  private void generateStructure4() {
    Structure.addPoint(x0, y0);             //Punkt 0
    Structure.addPoint(x0, y0 + h2);        //Punkt 1
    Structure.addPoint(x0, y0 + h2 + h1);   //Punkt 2
    //Verbinden
    Structure.addBeam(Structure.getPt(0), Structure.getPt(1), eModul, surface);
    Structure.addBeam(Structure.getPt(1), Structure.getPt(2), eModul, surface);

    double dx;
    for (int i = 0; i < nbElements; i++) {
      dx = x0 + (i + 1) * b;

      Structure.addPoint(dx, y0);                 //Punkt 3*i+3 (unten)
      Structure.addPoint(dx, y0 + h2);            //Punkt 3*i+4 (mitte)
      Structure.addPoint(dx, y0 + h2 + h1);       //Punkt 3*i+5 (oben)
      //Verbinden
      Structure.addBeam(Structure.getPt(3 * i + 5), Structure.getPt(3 * i + 4), eModul, surface);     //vertikal oben
      Structure.addBeam(Structure.getPt(3 * i + 4), Structure.getPt(3 * i + 3), eModul, surface);     //vertikal unten
      Structure.addBeam(Structure.getPt(3 * i + 5), Structure.getPt(3 * i + 2), eModul, surface);     //horizontal oben
      Structure.addBeam(Structure.getPt(3 * i + 4), Structure.getPt(3 * i + 1), eModul, surface);     //horizontal mitte
      Structure.addBeam(Structure.getPt(3 * i + 3), Structure.getPt(3 * i), eModul, surface);       //horizontal unten
      if ((i % 2) == 0) {
        Structure.addBeam(Structure.getPt(3 * i + 2), Structure.getPt(3 * i + 4), eModul, surface);     //Diagonal
        Structure.addBeam(Structure.getPt(3 * i + 1), Structure.getPt(3 * i + 3), eModul, surface);     //Diagonal
      } else {
        Structure.addBeam(Structure.getPt(3 * i), Structure.getPt(3 * i + 4), eModul, surface);       //Diagonal
        Structure.addBeam(Structure.getPt(3 * i + 1), Structure.getPt(3 * i + 5), eModul, surface);     //Diagonal
      }
    }

    //Lagerung festlegen
    //Anz. horiz. Balken: 3
    setFix(3);
    setForce(3);
  }

  //Struktur 5 generieren
  private void generateStructure5() {
    Structure.addPoint(x0, y0);             //Punkt 0
    for (int j = 1; j < nbElements0; j++) {
      Structure.addPoint(x0, y0 + j * h);   //Punkt N0i
      //Verbinden
      Structure.addBeam(Structure.getPt(j - 1), Structure.getPt(j), eModul, surface);
    }

    double dx;
    for (int i = 0; i < nbElements; i++) {
      dx = x0 + (i + 1) * b;
      Structure.addPoint(dx, y0);                 //Punkt unten
      //Verbinden
      Structure.addBeam(Structure.getPt(nbElements0 * i), Structure.getPt(nbElements0 * (i + 1)), eModul, surface);     //horizontal

      for (int j = 1; j < nbElements0; j++) {
        Structure.addPoint(dx, y0 + j * h);

        //Verbinden
        Structure.addBeam(Structure.getPt(nbElements0 * (i + 1) + (j - 1)), Structure.getPt(nbElements0 * (i + 1) + j), eModul, surface);     //vertikal
        Structure.addBeam(Structure.getPt(nbElements0 * i + j), Structure.getPt(nbElements0 * (i + 1) + j), eModul, surface);             //horizontal
        Structure.addBeam(Structure.getPt(nbElements0 * i + (j - 1)), Structure.getPt(nbElements0 * (i + 1) + j), eModul, surface);         //horizontal
        Structure.addBeam(Structure.getPt(nbElements0 * i + j), Structure.getPt(nbElements0 * (i + 1) + (j - 1)), eModul, surface);         //horizontal
      }
    }

    //Lagerung festlegen
    //Anz. horiz. Balken: nbElements0
    setFix(nbElements0);
    setForce(nbElements0);
  }

  //Lagerung festlegen
  //int nb: Anzahl horiz. Lagen
  private void setFix(int nb) {
    int pos;   //Pos. für Lager mit Auskragung
    if (nbElements == 1) {
      pos = nb;   //nb*i+3
    } else {
      pos = nb * Math.round((float) 0.7 * nbElements - 1);
    }

    //Lagerung festlegen
    Structure.getPt(0).setFixX(true);
    Structure.getPt(0).setFixY(true);
    //1) Einfacher Balken
    if (jRadioButton_Sys1.isSelected()) {
      Structure.getPt(nb * nbElements).setFixY(true);
      //2) Einfacher Balken + Auskragung
    } else if (jRadioButton_Sys2.isSelected()) {
      Structure.getPt(pos).setFixY(true);
      //3) Beidseitig eingespannt    
    } else if (jRadioButton_Sys3.isSelected()) {
      Structure.getPt(nb - 1).setFixX(true);
      Structure.getPt(nb - 1).setFixY(true);
      Structure.getPt(nb * nbElements + (nb - 1)).setFixX(true);
      Structure.getPt(nb * nbElements + (nb - 1)).setFixY(true);
      Structure.getPt(nb * nbElements).setFixX(true);
      Structure.getPt(nb * nbElements).setFixY(true);
      //4) Eingespannt + Auskragung
    } else if (jRadioButton_Sys4.isSelected()) {
      Structure.getPt(nb - 1).setFixX(true);
      Structure.getPt(nb - 1).setFixY(true);
      Structure.getPt(pos).setFixY(true);
      //5) Einseitig eingespannt
    } else if (jRadioButton_Sys5.isSelected()) {
      Structure.getPt(nb - 1).setFixX(true);
      Structure.getPt(nb - 1).setFixY(true);
      //6) Alle Punkte fixiert (unten)
    } else {
      for (int i = 0; i <= nbElements; i++) {
        Structure.getPt(nb * i).setFixX(true);
        Structure.getPt(nb * i).setFixY(true);
      }
    }
  }

  //Kräfte festlegen
  //int nb: Anzahl horiz. Lagen
  private void setForce(int nb) {
    int pos;
    //Gleichmässig verteilte Last
    if (jRadioButton_f1.isSelected()) {
      Structure.getPt(nb - 1).setForceY(f);
      for (int i = 1; i <= nbElements; i++) {
        Structure.getPt(nb * i + (nb - 1)).setForceY(f);
      }
      //Einzellast Mitte
    } else if (jRadioButton_f2.isSelected()) {
      if ((nbElements % 2) == 0) {
        pos = nbElements / 2;
        Structure.getPt(nb * pos + (nb - 1)).setForceY(f);
      } else {
        pos = (nbElements - 1) / 2;
        Structure.getPt(nb * pos + (nb - 1)).setForceY(f / 2);
        Structure.getPt((nb + 1) * pos + (nb - 1)).setForceY(f / 2);
      }
      //Verteilte Last + Einzellast
    } else if (jRadioButton_f3.isSelected()) {
      Structure.getPt(nb - 1).setForceY(f);
      for (int i = 1; i <= nbElements; i++) {
        Structure.getPt(nb * i + (nb - 1)).setForceY(f);
      }
      if ((nbElements % 2) == 0) {
        pos = nbElements / 2;
        Structure.getPt(nb * pos + (nb - 1)).setForceY(f0);
      } else {
        pos = (nbElements - 1) / 2;
        Structure.getPt(nb * pos + (nb - 1)).setForceY(f0 / 2);
        Structure.getPt((nb + 1) * pos + (nb - 1)).setForceY(f0 / 2);
      }
      //Verteilte horiz. + vert. Last
    } else {
      for (int i = 0; i <= nbElements; i++) {
        Structure.getPt(nb * (i + 1) - 1).setForceX(f0);
        Structure.getPt(nb * (i + 1) - 1).setForceY(f);
      }
    }
  }
}
