//Autor: Manuel Schmocker
//Datum: 24.02.2014

package ch.manuel.structurecalc2d;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//Eingabefeld für "Querschnitt"
public class NewJDialog2 extends javax.swing.JDialog {
    private static int TABLE_WIDTH;                  //Breite Tabelle (wird in "jScrollPane1" integriert
    
    //Konsturktor des Eingabefeldes
    public NewJDialog2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addTable();                             //Tabelle im Rahmen "jScrollPane1" integrieren
        TABLE_WIDTH = jScrollPane1.getWidth();  //Breite Tabelle festlegen
        
        //Position Fenster festlegen
        int width = this.getWidth();
        int hight = this.getHeight();
        java.awt.Dimension d = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int) ((d.getWidth() - width)/2), (int) ((d.getHeight() - hight)/2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("Querschnitt bearbeiten");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Querschnitt:");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Neuer Querschnitt:");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("1000.0");

        jLabel2.setText("E-Modul [GPa]");

        jLabel3.setText("Fläche A [mm2]");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("210000.0");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Hinzufügen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Löschen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                            .addComponent(jButton4))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1)))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Button pressed: OK
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Button pressed: Hinzufügen
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String str1, str2;
        boolean cond = true;
        double mod = 0;
        double surf = 0;
        
        //E-Modul auslesen
        str1 = jTextField1.getText();
        if (MyUtilities.isNumeric(str1)) {
            surf = Double.parseDouble(str1);
        } else {
            cond = false;
            MyUtilities.getErrorMsg("Eingabefehler", "Eingabe überprüfen: " + str1);
        }
        //Fläche auslesen
        str2 = jTextField2.getText();
        if (MyUtilities.isNumeric(str2)) {
            mod = Double.parseDouble(str2);
        } else {
            cond = false;
            MyUtilities.getErrorMsg("Eingabefehler", "Eingabe überprüfen: " + str2);
        }
        
        //Falls kein Fehler beim Einlesen: Eintragen Liste "listSections"
        if (cond) {
            addValue(surf, mod);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //Butten pressed: Löschen
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getSectionDelDialog();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    // Variables declaration - Eigene Variablen
    private static javax.swing.JTable jTable1;
    private static DefaultTableModel tableModel1;
    
    // Beschriftung Titel Tabelle
    final private String titel_11 = "Nr.";
    final private String titel_12 = "Fläche A [mm2]";
    final private String titel_13 = "E-Modul [MPa]";
    final private int defaultNumbersOfRows = 0;
    
    //Wertepaar in erstellen und in Tabelle einfügen
    public static void addValue(double surf, double mod) {
        Structure.getSections().add(new Double[] {surf, mod});
        setContentTable();
    }
    
    // Methode zum Einfügen der Tabelle in das entsprechende ScrollPanes
    private void addTable() {
        // Tabelle 1
        tableModel1 = new javax.swing.table.DefaultTableModel(new String[]{titel_11, titel_12, titel_13}, defaultNumbersOfRows);
        jTable1 = new javax.swing.JTable();
        jTable1.setModel(tableModel1);
        
        //jTable1.setColumnSelectionAllowed(false);     //Nicht notwendig, da "setEabled = false"
        //jTable1.setRowSelectionAllowed(true);         //Nicht notwendig, da "setEabled = false
        jTable1.setEnabled(false);
        
        jTable1.setPreferredSize(jScrollPane1.getSize());
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(140);
        
        jScrollPane1.setViewportView(jTable1);
    }

    //Methode zum Füllen der Tabelle mit E und A
    public static void setContentTable() {
        //Tabelle leeren
        for(int i = (tableModel1.getRowCount() - 1); i >= 0; i--){
            tableModel1.removeRow(i);
        }
        
        //Tabelle mit Werten füllen
        for (int i = 0; i < Structure.getSections().size(); i++) {
            tableModel1.addRow(new Object[]{""});   //Neue Reihe
            jTable1.setValueAt(i+1, i, 0);                                      //1. Spalte: Nr
            jTable1.setValueAt(Structure.getSections().get(i)[0], i, 1);        //2. Spalte: Fläche
            jTable1.setValueAt(Structure.getSections().get(i)[1], i, 2);        //3. Spalte: E-Modul
        }
        jTable1.setPreferredSize(new java.awt.Dimension(TABLE_WIDTH, tableModel1.getRowCount()*jTable1.getRowHeight()));
    }
    
    //Eingabefenster zum Löschen Querschnitt (A und E) "Section"
    public static void getSectionDelDialog(){
        String txt;                     //Rückgabe Dialog
        int nb = Structure.getSections().size();    //Anzahl Objekt
        String obj[] = new String[nb];  //Liste für Auswahl erstellen "section"
        
        //Wenn kein Eintrag in der Tabelle -> Keine Aktion durchführen
        if (nb != 0) {
            //Auswahl "selection" erstellen
            for (int i = 0; i < nb; i++){
                obj[i] = Integer.toString(i+1);
            }

            txt = (String) JOptionPane.showInputDialog(
                    null,                           //parentComponent
                    "Querschnitt Wählen:",          //message
                    "Querschnitt löschen",          //title
                    JOptionPane.PLAIN_MESSAGE,      //message type
                    null,                           //icon
                    obj,                            //selection Values
                    obj[0]);                         //initial Value

            if ( txt == null ){     //Dialog Schliessen bei Abbruch: True
                //nichts...
            } else {
                 //Reihe in Tabelle löschen
                int pos = Integer.parseInt(txt) - 1;
                Structure.getSections().remove(pos);
                setContentTable();
            }
        }
    }
    
    
}
